# -*- coding: utf-8 -*-
"""2nd-SpamHamEmailsModel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XdDISjmTG3jTSybIoMGQdeF3xeuVmGkX

**Train the Model for Spam / Ham Emails using Logistic Regression Algorithm**

**Description of Spam/Ham Datadet**

I download the Dataset from Kaggle.com
***About Dataset***
The Spam Assassin Dataset is a a selection of mail messages, suitable for use in testing spam filtering systems. https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset
"""

import numpy as np
import pandas as pd

# loading the dataset
df = pd.read_csv("/content/drive/MyDrive/SpamHamModel/spam.csv",
                 encoding="latin1")
df.head(10)

"""**1-Data Cleaning**"""

df.info()

# delete the unnecessary columns
df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace=True)
df.head(3)

# Rename the columns for better under standing of Data that it contain
df.rename(columns={'v1':'target', 'v2':'text'}, inplace=True)
df.head(3)

# Encode Spam=1 and Ham=0
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['target'] = encoder.fit_transform(df['target'])
df.head(5)

# Checking - How many rows and columns?
print(df.shape)

# Checking - How many missing values?
df.isnull().sum()

# Delete the rows which have any missing value
df.dropna(axis=0, inplace=True)

# # Checking - How many rows and columns?
print(df.shape)

# Checking for duplicate values
df.duplicated().sum()

# reomve the duplicate values
df = df.drop_duplicates(keep='first')

# Again Check duplacate values
df.duplicated().sum()

# Again Checking - How many rows and columns?
print(df.shape)

# Print the first record of dataset for observation
print(df.iloc[0]['text'])

"""**EDA - Exploratory Data Analysis**"""

# count the no of values of Spam & Ham
df['target'].value_counts()

# Draw a pie chart which represent % of ham & spam
import matplotlib.pyplot as plt
plt.pie(df['target'].value_counts(), labels=['Ham' , 'Spam'], autopct="%0.2f%%")
plt.show()

# Data is imbalance because Ham is 87.37% and Spam 12.63%

# Now find no. of sentences, no of words, no of characters in messages
!pip install nltk

import nltk
nltk.download('punkt_tab')

# no of numeric characters
df['numeric_characters']= df['text'].apply(len)
df.head(3)

# find no of words
from nltk.tokenize import word_tokenize
df['no_words'] = df['text'].apply(lambda x:len(word_tokenize(x)))
df.head(3)

# find no of sentences
df['no_sentences'] = df['text'].apply(lambda x:len(nltk.sent_tokenize(x)))
df.head(3)

# Analysis of columns numeric_characters, no_word , no_sentences
df[['numeric_characters' , 'no_words' , 'no_sentences']].describe()

# analysis of Spam messages
df[df['target'] == 1][['numeric_characters' , 'no_words' , 'no_sentences']].describe()

# analysis of Ham messages
df[df['target'] == 0][['numeric_characters' , 'no_words' , 'no_sentences']].describe()

# Observe that :: no of characters,word,sentences in Spam messages more than no of characetrs,words,sentences in Ham messgaes

# Analysis by Histogram :: no of characters
import seaborn as sns
plt.figure(figsize = (12,10))
sns.histplot(df[df['target'] == 0]['numeric_characters'], color = 'red')
sns.histplot(df[df['target'] == 1]['numeric_characters'], color = 'yellow')

# observe that :: no of characters in Spam messages more than no of characetrs in Ham messages

# Analysis by Histogram :: no of words
plt.figure(figsize = (12,10))
sns.histplot(df[df['target'] == 0]['no_words'], color = 'red')
sns.histplot(df[df['target'] == 1]['no_words'], color = 'yellow')

# observe that :: no of words in Spam messages more than no of words in Ham messages

# Analysis by Histogram :: no of sentences
plt.figure(figsize = (12,6))
sns.histplot(df[df['target'] == 0]['no_sentences'], color = 'red')
sns.histplot(df[df['target'] == 1]['no_sentences'], color = 'yellow')

# observe that :: no of sentences in Spam messages more than no of sentences in Ham messages

# find the relationship between 3 columns no_word, numeric_characters, no_sentences by pair graph
sns.pairplot(df,hue='target')

# observation : strong +ve correlation between numeric_characters and no_words means - messages contain more words and more characters
# spam messgaes are clustered at higher values of numeric_characters, no_words, and no_sentences
# there are some messages overlap between Spam nad Ham , but spam messages are more concentrated in the higher ranges of these features

df.columns

# find correlation (+ve / -ve relationship between columns)
df[['target','numeric_characters', 'no_words', 'no_sentences']].astype(int)
df[['target','numeric_characters', 'no_words', 'no_sentences']].corr()
#sns.heatmap(df.corr(),annot=True)

sns.heatmap(df[['target','numeric_characters', 'no_words', 'no_sentences']]
            .corr(), annot=True)

#observations : numeric_characters and no_words have a very strong positive correlation (0.97), meaning messages with more words almost always contain more characters.
#no_sentences has a moderate positive correlation with numeric_characters (0.62) and no_words (0.68), indicating that longer messages tend to have more sentences.
#The target column has a weak positive correlation with all three features (0.26–0.38), suggesting that spam messages are generally longer, but these features alone are not sufficient for perfect classification.

"""**I go for Best feature: numeric_characters (highest correlation with target = 0.38) Also useful: no_words**

**2-Data Processing**
"""

import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('punkt_tab')
stopwords.words('english')
import string
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

# Function for text processing
def text_processing_f(text):

    # 1-convert to lower case
    text = text.lower()

    # 2-Tokenize the words
    text = nltk.word_tokenize(text)

    # remove the special characters
    text = [word for word in text if word.isalnum()]

    #3-remove stopwords(eg a,is,the,for,on etc)
    # remove Punctuations(!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~)
    text = [word for word in text
           if word not in stopwords.words('english') and
            word not in string.punctuation]

    # 6-Stemming (eg. Dance,Dancing,danced convert to dance)
    text = [ps.stem(word) for word in text]


    return " ".join(text)

"""**Check text_processing_f  FUNCTION**"""

text_processing_f('Where the Lahori looking %%  & # 3446 ? ')

df['text'][3000]
#I sent you  &lt;#&gt;  bucks

df['processed_text'] = df['text'].apply(text_processing_f)

df.head(5)

"""**Generate the word cloud of Spam Messages & Not Spam Messages**"""

import matplotlib.pyplot as plt
from wordcloud import WordCloud
wc = WordCloud(
            width=1000,
            height=1000,
            min_font_size=12,
            background_color='black'
            )
spam_wc = wc.generate(df[df['target']==1]['processed_text'].str.cat(sep=' '))
plt.imshow(spam_wc)

#observation :: free, call, txt, claim, reply, and win, indicating that spam messages

not_spam_wc=wc.generate(df[df['target']==0]['processed_text'].str.cat(sep=' '))
plt.imshow(not_spam_wc)

# #obsevation :: ok, will, call, now, and go, indicating that most ham messages

"""**Find Top 20 common words of spam messages**"""

# find how many words in spam messages?
spam_top_w = []
# convert all processed text messages in list
for msg in df[df['target']==1]['processed_text'].tolist():
    for word in msg.split():
        spam_top_w.append(word)
len(spam_top_w)

# list of top 20 spam words
from collections import Counter
df_spam_top_w = pd.DataFrame(Counter(spam_top_w).most_common(20))
print(df_spam_top_w)

import seaborn as sns
sns.barplot(x=0,y=1,data=df_spam_top_w, color='red')
plt.xticks(rotation = 'vertical')
plt.show()

"""**Find Top 30 common words of ham messages**"""

# find how many words in spam messages?
ham_top_w = []
# convert all processed text messages in list
for msg in df[df['target']==0]['processed_text'].tolist():
    for word in msg.split():
        ham_top_w.append(word)
len(ham_top_w)

# list of top 20 ham words
from collections import Counter
df_ham_top_w = pd.DataFrame(Counter(ham_top_w).most_common(20))
print(df_ham_top_w)

df_ham_top_w = pd.DataFrame(Counter(ham_top_w).most_common(20))
sns.barplot(x=0,y=1,data=df_ham_top_w, color='green')
plt.xticks(rotation = 'vertical')
plt.show()

"""# **Build the Model**"""

# vectorize the text column because text column must be in numbers
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
cv = CountVectorizer()
tfidf = TfidfVectorizer(max_features=3000)

X = tfidf.fit_transform(df['processed_text']).toarray()
print(X)
print(X.shape)

y = df['target'].values
print(y)
print(y.shape)

"""**Split The Dataset by 80/20 rule**"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=2)

"""**Fit the Model**"""

# select the algorithms to train model
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score
gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

gnb.fit(X_train, y_train)
y_predict_gnb = gnb.predict(X_test)
print("accuracy score   : " , accuracy_score(y_test, y_predict_gnb))
print("confusion matrix :\n " , confusion_matrix(y_test, y_predict_gnb))
print("Precision score  : " , precision_score(y_test, y_predict_gnb))

mnb.fit(X_train, y_train)
y_predict_mnb = mnb.predict(X_test)
print("accuracy score   : " , accuracy_score(y_test, y_predict_mnb))
print("confusion matrix :\n " , confusion_matrix(y_test, y_predict_mnb))
print("Precision score  : " , precision_score(y_test, y_predict_mnb))

bnb.fit(X_train, y_train)
y_predict_bnb = bnb.predict(X_test)
print("accuracy score   : " , accuracy_score(y_test, y_predict_bnb))
print("confusion matrix :\n " , confusion_matrix(y_test, y_predict_bnb))
print("Precision score  : " , precision_score(y_test, y_predict_bnb))

# try to Train the model on different algorithms
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from xgboost import XGBClassifier

# initialize the algorithms
lr = LogisticRegression(solver='liblinear', penalty='l1')
svc = SVC(kernel = 'sigmoid', gamma=1.0)
linear_svc = LinearSVC(random_state=0, tol=1e-5)
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth=5)
knc = KNeighborsClassifier()
rfc = RandomForestClassifier(n_estimators=50, random_state=2)
abc = AdaBoostClassifier(n_estimators=50, random_state=2)
gbc = GradientBoostingClassifier(n_estimators=50, random_state=2)
bgc  = BaggingClassifier(n_estimators=50, random_state=2)
etc = ExtraTreesClassifier(n_estimators=50, random_state=2)
xgb = XGBClassifier(n_estimators=50, random_state=2)

# make classifiers dictionary
classifiers = {
    'LogisticRegression'         : lr,
    'SVC'                        : svc,
    'LinearSVC'                  : linear_svc,
    'MultinomialNB'              : mnb,
    'DecisionTreeClassifier'     : dtc,
    'KNeighborsClassifier'       : knc,
    'RandomForestClassifier'     : rfc,
    'AdaBoostClassifier'         : abc,
    'GradientBoostingClassifier' : gbc,
    'BaggingClassifier'          : bgc,
    'ExtraTreesClassifier'       : etc,
    'XGBClassifier'              : xgb
}

# make a function that predict train data and test data and find sccuracy score and precision for all selected algorithms
def train_classifier_f(clf, X_train, y_train, X_test, y_test):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)

    return accuracy, precision

accuracy_scores = []
precision_scores = []

for name, clf in classifiers.items():
        current_accuracy, current_precision = train_classifier_f(clf, X_train,y_train, X_test, y_test)

        print("For" , name)
        print("Accuracy" , current_accuracy)
        print("Precision" , current_precision)

        accuracy_scores.append(current_accuracy)
        precision_scores.append(current_precision)

# make data frame for accuracy score and precision
performance_df = pd.DataFrame({'Algorithm':classifiers.keys(),
                             'Accuracy':accuracy_scores,
                             'Precision':precision_scores}).sort_values('Precision',ascending=False)
performance_df = performance_df.set_index('Algorithm')
performance_df.head(10)

"""# I Select the Model 'multinomialNM' with Tfidf vectorizer
because

*   text dataset more rely on precision is 100%
*   Accuracy is also nearest 100%



"""

# Save the model
import joblib
joblib.dump(mnb, open('/content/drive/MyDrive/SpamHamModel/2nd-SpamHamEmailsTrainedModel.joblib', 'wb'))
joblib.dump(tfidf, open('/content/drive/MyDrive/SpamHamModel/vectorizerTfidf.joblib', 'wb'))

